name: Android CI/CD (Debug)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and Deploy Debug APK to Firebase
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup JDK 17
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      # Setup Gradle cache
      - name: Cache for gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Load google-services.json
      - name: Load Google Service file
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA | base64 -di > app/google-services.json

      # Create local.properties with secrets
      - name: Create local.properties with secrets
        run: |
          echo "API_URL=${{ secrets.API_URL }}" >> local.properties
          echo "GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }}" >> local.properties
          echo "GOOGLE_DIRECTION_API_KEY=${{ secrets.GOOGLE_DIRECTION_API_KEY }}" >> local.properties

      # Grant execute permission to gradlew
      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      # Build APK debug version (without signing)
      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace --info

      # Check Output Debug APK
      - name: Debug Output
        run: ls -R app/build/outputs/apk/debug/app-debug.apk

      # Get latest commit message and send to Firebase release notes
      - name: Get release notes
        id: release_notes
        run: |
          echo "::set-output name=Release_Notes::${{ github.event.head_commit.message }}

      # Deploy to Firebase App Distribution (debug version)
      - name: Deploy to Firebase (Debug)
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: belajar-ci-cd
          file: app/build/outputs/apk/debug/app-debug.apk
          releaseNotes: ${{ steps.release_notes.outputs.Release_Notes }}
